# This site uses MkDocs for documentation generation
# See mkdocs.yml for the actual configuration

title: Annie.io
description: "Blazingly fast Approximate Nearest Neighbors in Rust"
baseurl: ""
url: "https://annie.io"

# Exclude MkDocs files from Jekyll processing
exclude:
  - mkdocs.yml
  - docs/
  - site/
  - requirements.txt
  - .gitignore
  - README.md
