site_name: Annie.io
site_description: Blazingly fast Approximate Nearest Neighbors in Rust
site_url: https://annie-docs.netlify.app/
repo_url: https://github.com/Programmers-Paradise/Annie-docs
repo_name: Programmers-Paradise/Annie-docs
edit_uri: edit/main/docs/


theme:
  name: material
  logo: assets/logo.png  
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.code.annotate
    - content.code.highlight
    - content.code.line_numbers
    - palette.toggle
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
  font:
    text: Inter
    code: Fira Code

# Add analytics and feedback widgets
extra_javascript:
  - assets/analytics.js
  - assets/interactive-examples.js

nav:
  - Home: index.md
  - Benchmarks: benchmarks.md
  - Tutorials:
      - Overview: tutorials/index.md
      - Beginner:
          - Getting Started: tutorials/01-getting-started.md
          - Indexing Your First Dataset: tutorials/02-indexing-basics.md
          - Performing Your First Search: tutorials/03-basic-search.md
          - Saving and Loading Indexes: tutorials/04-saving-loading.md
          - Batch Operations: tutorials/05-batch-operations.md
      - Intermediate:
          - Using Annie in Production: tutorials/06-production-usage.md
          - Filtering and Metadata: tutorials/07-filtering-metadata.md
          - Debugging and Troubleshooting: tutorials/08-debugging.md
      - Advanced:
          - Custom Distance Metrics: tutorials/09-custom-metrics.md
          - GPU Acceleration: tutorials/10-gpu-usage.md
          - Performance Optimization: tutorials/11-performance.md
      - Use Cases:
          - Recommendation System: tutorials/usecase-recommendation.md
          - Image Search: tutorials/usecase-image-search.md
  - FAQ: faq.md
  - Troubleshooting: troubleshooting.md
  - API Reference:
      - AnnIndex: api/ann_index.md
      - PyHnswIndex: api/hnsw_index.md
      - ThreadSafeAnnIndex: api/threadsafe_index.md
  - Features:
      - Concurrency: concurrency.md
      - Filtered Search: filtering.md
  - Examples: examples.md
  - Contributing: contributing.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite:
      guess_lang: false

plugins:
  - search

# Copy extra files to site directory
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Programmers-Paradise/Annie
      name: GitHub
  
# Directory where the documentation source files are located
docs_dir: docs

# Directory where the built site will be located
site_dir: site
