[build]
  publish = "site"
  command = "python3 -m pip install --upgrade pip && pip install -r requirements.txt && mkdocs build --verbose && cp docs/_redirects site/_redirects && cp docs/robots.txt site/robots.txt"

[build.environment]
  PYTHON_VERSION = "3.11"
  PIP_UPGRADE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"
