name: Lighthouse CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Install Lighthouse CI
      run: npm install -g @lhci/cli@0.12.x

    - name: Build site
      run: |
        npm run build # change this if your site build command is different

    - name: Run Lighthouse CI
      run: |
        lhci autorun
