name: Sync API Docs

permissions:
  contents: write

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-api-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run API doc sync script
        run: |
          python scripts/sync-api-docs.py
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(docs): auto-sync API documentation"
          branch: main
          file_pattern: 'docs/api/*.md'
